### ISSUE TITLE
Building on arm64 (raspberry pi 4) fails.

### ISSUE THREAD

**Issue by nikolasdmtr** [ki-editor/ki-editor#325]
Following the installation instructions to build on a raspberry pi 4, I get:
 
error: failed to run custom build command for `openssl-sys v0.9.101`

**Comment by wongjiahau** [comment]
Can you try to run this and install it again?
```
sudo apt-get update
sudo apt-get install libssl-dev
```

**Comment by nikolasdmtr** [comment]
I did and it completed the installation succesfully. Thank you!
