### ISSUE TITLE
Keybinding help with `@n` panics

### ISSUE THREAD

**Issue by ilyagr** [ki-editor/ki-editor#332]
After looking through the source code, I was excited to discover that the `@` keybinding is supposed to show keybinding help. However, pressing `@n` for normal mode bindings resulted in a panic:

```
thread 'main' panicked at src/components/keymap_legend.rs:235:26:
                                                                   called `Result::unwrap()` on an `Err` value: Syntax(
                                                                                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                              regex parse error:
                                                                                                    ( → Cycle primary selection (?<hint>\()backward\)
                                 ^
                                  error: unclosed group
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              )
               note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I suspect the intent was to disable this feature for now, until it works better (since it doesn't seem to be documented).

As an aside, I think having this feature work and advertised prominently (e.g. as `:help` and/or in the Space menu) would be very helpful.

**Comment by wongjiahau** [comment]
Yup, it’s undocumented because @ is a weird keybinding, what do you think of `space ?`?

**Comment by ilyagr** [comment]
`space ?` sounds great to me. I vaguely remember that Spacemacs or Doom Emacs might have used that.

**Comment by wongjiahau** [comment]
Do you want to give it a try?

**Comment by ilyagr** [comment]
Maybe at some point, but no promises. I'm more worried about the panic than the binding, by the way.

**Comment by ilyagr** [comment]
OK, I did find a quick fix to the panic in #334 :). I'm not sure it solves the issue completely.

I'm still not sure this "works": how do I scroll through the resulting window after I press `@n`?

**Comment by wongjiahau** [comment]
> I'm still not sure this "works": how do I scroll through the resulting window after I press `@n`?

The answer lies in "Every component is an editor".

After you press `@n`, you can press `esc` to enter normal mode, and then use `ctrl+d`/`ctrl+u` to scroll down and up.

If you want to execute any keybindings, enter insert mode (either `i`/`a`), then press the key.

**Comment by ilyagr** [comment]
Ah, thanks!

I didn't realize that because if I press any key other than `esc` (e.g. `j`), the window disappears. There seems to be a werid third mode (not insert and not normal) that the window is in before I press `esc`. Or maybe the other (invisible) window is active?

**Comment by wongjiahau** [comment]
I see where you're coming from, the weird third mode is the Insert mode being overridden to execute the keybindings. So technically speaking, the Keymap Legend component is an Editor **but** its Insert Mode is modified.

**Comment by wongjiahau** [comment]
For example, when you press `j` in the Insert Mode of the Keymap Legend component, it will closes itself, and execute `j` (Move selection Down) on its parent editor.

**Comment by ilyagr** [comment]
I see, this certainly will help me navigate.

--------

Now, for some vague ideas.

Perhaps there could be an explicit "menu mode". It's also a bit weird to have an "insert mode" in a read-only window.

I've also noticed that the mode you end up after pressing `/` is also a bit weird. I'm guessing it's the same situation, but calling it "Search mode" and providing some way to get help on it would help. I don't immediately see a way to make all of these weird modes consistent with each other, but maybe that's OK. Sharing Normal mode with your "everything is a buffer" philosophy makes sense to me (though I haven't explored it enough to have a strong opinion).

Coming from another direction, it would be nice if PageUp and PageDown worked, and maybe Vim's Ctrl+f/Ctrl+b.

Moreover, perhaps there could be a keybinding for paging the "other window" (like a menu or the settings after `g,`). This would be a bit tricky, since the "other window" would have to be highlighted somehow when more than two windows are open (which often happens when I search with options).
