### ISSUE TITLE
Case Agnostic mode is confusing (was: Regex search mode seems to always be case agnostic)

### ISSUE THREAD

**Issue by ilyagr** [ki-editor/ki-editor#333]
I searched for `Dispatch\b` and then pressed `gx` to make it a Regex search.

I have `dispatch` highlighted as a match, even though the search is supposedly not case agnostic.

**Update:** In fact, I'm getting something similar for literal search as well. Also, after search settings are changed, the search doesn't seem to be updated correctly (though I'm not sure enough what happens to file a bug report).

**Comment by wongjiahau** [comment]
Hey @ilyagr, I think there’s some misunderstanding here, to enter Regex mode you should press `g , x`, did you press the comma?

**Comment by ilyagr** [comment]
Yes, that's what I meant, sorry.

I now notice that there are two similar-looking options: `g,c` for "Case Agnostic" and `g,i` for "Case-sensitive". The latter seems to work OK. The former seems weird and confusing. Perhaps it should be removed?

**Comment by wongjiahau** [comment]
They have different purposes, because case-agnostic doesn’t mean uppercase or lowercase, it means kebab case, snake case, pascal case and etc. 

For example, in case-agnostic mode, searching `hello world` matches `hello_world`, `HelloWorld`, `hello-world` and etc.

I guess I might need a better name for “case-agnostic”, do you have any recommendations?

**Comment by ilyagr** [comment]
Ah, that's tricky. The first suggestion that comes to mind is to call it "Join Words" and explain it in detail in the docs.

**Comment by wongjiahau** [comment]
How about "Naming-convention agnostic"?

**Comment by ilyagr** [comment]
That's better than "Case Agnostic", though still quite confusing.

Another idea I had: "Identifier From Words". Or maybe "Identifier From Joined Words"?

I'll let you know if something else comes to mind.
