### ISSUE TITLE
Repurpose `o` and `shift-o` to mean "open below and above selection respectively"

### ISSUE THREAD

**Issue by jbhoot** [ki-editor/ki-editor#340]
Opening an issue so that I don't forget about the rationale, even if we don't work on it right away.

`o` is at best useless and at worst obstructive when selection mode is either of column, word, and token mode.

It is also inconsistent in that `.`. and `,` works across lines, but `o` does not do the same for the above-mentioned selection modes.

I think the current reading of `o`/`shift-o` is to insert before/after the selected unit of the current selection mode, respectively. However, `i` and `a` already do that, and does it consistently.

I suggest that we repurpose `o`/`shift-o` to mean insert below/above current selection respectively. This also makes `o` more compatible with vim.

**Comment by wongjiahau** [comment]
I agree, but can we keep its existing behavior when the selection mode is Syntax Node?

**Comment by jbhoot** [comment]
That would defeat the purpose of unifying the function of `o` - opening the current selection mode on new line (or below and above).

> I agree, but can we keep its existing behavior when the selection mode is Syntax Node?

Isn't what you want achievable with `i` and `a`?

In any case, if you are reluctant about this proposal, then I suggest that we either change this for all modes or for none for the time being.

**Comment by wongjiahau** [comment]
You’re right, having a special case here could be very surprising.

Let’s dedicate `o` solely to lines then. 

Would you like to create a PR for this?

**Comment by jbhoot** [comment]
I will add to the rationale for posterity:

To my mind, we aren't even breaking the Ki abstractions you created in form of the selection modes. The re-purposed `o` and `O` would in fact adhere to them. I see `i`, `a`, `o`, `O` as ways to choose where to open editing around the current selection.

Even vim defines `o` as:

> Begin a new line below the cursor and insert text...

and `i` as:

> Insert text before the cursor...

If anything, re-purposed `o` we be closer to those definitions: "Begin a new line below the current selection and insert text".
