### ISSUE TITLE
Changelog 

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [ki-editor/ki-editor#372]
Is there somewhere I can watch project changes?

I really like the concept of this editor and would like to monitor its progress. I was hoping there might be a `CHANGELOG` or release notes to check out. I've preemptively subscribed to your github releases.

Likely you haven't made any releases yet (?), but it might be reasonable to make an alpha release and start keeping a changelog?

**Comment by wongjiahau** [comment]
Hey Mirko I think I can make an alpha release after a major changes that
I’ve been working on.

In terms of the changes unfortunately you have to rely on the commit
history for now.

**Comment by wongjiahau** [comment]
@Mirko-von-Leipzig I have zero experience in releasing an alpha release, do you have any suggestions on what should be prepared before doing so?

**Comment by Mirko-von-Leipzig** [comment]
Sure no problem :) In general an alpha release is very much the same as a normal release except people shouldn't expect it to work perfectly. As such, its really no different from however you want to create a release normally, except you'll tag/name the release slightly differently. e.g. `x.y.z-alpha_0`.

You could also simply release as `0.1.0` for now and increment `0.1.x` each time, and not bother with the `-alpha` style suffix. Having a pre-1.0 numbering scheme should already indicate that things are under development still :)

Any release should at least have:

- a tag on github
- release notes 

I would suggest having a changelog (https://keepachangelog.com/en/1.1.0/) in place. For the first "release" you can simply have it an empty `[v0.1.0]` section, but then following that ideally you'd fill in the `[unreleased]` section with the changes as you make them.

I can elaborate more if you like; but honestly so long as the commit is tagged people can find a specific version to install however they want. And the changelog will inform them of the changes between two versions. In the long run you can automate the release process once you've found something you like.

**Comment by wongjiahau** [comment]
Thanks for the guidance! That sounds less daunting than I expected,
especially the part where I can leave the first version empty.

**Comment by wongjiahau** [comment]
@Mirko-von-Leipzig how often should I create a new release?

**Comment by Mirko-von-Leipzig** [comment]
> @Mirko-von-Leipzig how often should I create a new release?

That's completely up to you, and will likely change over time as your project matures.

Initially you might create a release whenever

- you decide you have enough new changes/features, or
- there was a critical bugfix that should be released ASAP

Bear in mind that this is your project and your time, so do whatever you find easy and convenient.
