### ISSUE TITLE
feat(multi-cursor): split by lines, syntax elements, regex, etc.

### ISSUE THREAD

**Issue by ilyagr** [ki-editor/ki-editor#387]
I think it'd be cool and very natural if `ql` split each selection into a selection per line, `qs` split it by syntax element, and a subsequent `qb` split it by smaller syntax elements.

In Kakoune, I constantly use the Alt-S command to split a selection by lines, which can be followed by Alt-K to keep some of the lines. The latter already exists in Ki, but I didn't find an analogue for the former.

Then, `q/` would become an analogue of Kakoune's `s` command. We'd need another feature for Kakoune's `S` command (probably a new selection mode that selects everything *between* matches of regexes, generalizing the word/line selection mode).

Reference for Kaknoune's commands: https://github.com/mawww/kakoune/blob/master/doc/pages/keys.asciidoc, https://raw.githubusercontent.com/mawww/kakoune/refs/heads/master/doc/pages/keymap.asciidoc (may need to zoom out). I think Helix uses the same bindings for many of the ones I mentioned, but I'm not sure.

I didn't quite understand https://github.com/ki-editor/ki-editor/issues/241, so I'm not sure how my suggestion is related to it.

**Comment by wongjiahau** [comment]
I had this in mind for a long time, this is how I envision it to work, it's very similar to what you had:

1. A key (perhaps `Q`) starts a Split Session
2. A Split Session will wait for a `SetSelectionMode` command
3. Then it will split the selections based on the selection mode carried by the `SetSelectionMode` command

For example, to split the current selection by lines:
```
Q e
```

To split the current selection by `foo`:
```
Q / f o o enter
```

To split the current selection by the previous search:
```
Q ] p
```

By the way, do you know that pressing `space a` in Syntax Node selection mode add cursors to every sibling nodes?
