### ISSUE TITLE
Bug in Introduction Page on github.io site

### ISSUE THREAD

**Issue by tuftman-0** [ki-editor/ki-editor#445]
on the site: https://ki-editor.github.io/ki-editor/docs/introduction
in the section
Sorting TODO list based on completion
when the key sequence reaches e
The editor shows the error
```
Unable to obtain slice for range: CharIndexRange {
    start: CharIndex(
        188,
    ),
```
and the rest of the simulation appears to fail with a few more errors

**Comment by wongjiahau** [comment]
Thanks for reporting this issue!
