### ISSUE TITLE
Configuration PR proposal

### ISSUE THREAD

**Issue by LiGoldragon** [ki-editor/ki-editor#451]
Hi! I was excited to find this project, as I'm looking for a better editor to integrate with my project. Our philosophy is very compatible. I will eventually develop a new way to generate rust code, which is in line with an editor that is configured at compile-time. Would you be open to a PR to allow the configuration of keymaps? It would create a new complex type (struct), to select a different layout at compile-time, which can also later easily allow changing the keymaps at run-time. Thank you :pray:

**Comment by wongjiahau** [comment]
That's interesting, would you mind if we start with something small like configuring the theme?

**Comment by LiGoldragon** [comment]
Good idea!

**Comment by wongjiahau** [comment]
Actually now I just remember that the LSP config will be a great use case because it should be configurable at runtime, and would benefit tremendously from the static type-checking.

**Comment by LiGoldragon** [comment]
I spent a day looking at the code, and decided not to pursue this. Nice project. Thank you :pray:
