### ISSUE TITLE
feat(open file): fzf match on whole path

### ISSUE THREAD

**Issue by skariel** [ki-editor/ki-editor#472]
currently match is on file base name and directory separately. For e.g. say I have a file `ssh_server/main.go` and I type `shm` it will not match. Typing `ma` will match it on base name, however it will also match other `main`s in other folders.

**Comment by jcowgar** [comment]
I have found this too. You can type sh<space>m to help narrow it down.

**Comment by skariel** [comment]
yeah that actually solves it very nicely. Closing this issue :)
